name: spareparts
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_core_web: ^2.11.4
  cupertino_icons: ^1.0.2
  path: ^1.9.0
  #
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20
  shared_preferences: ^2.2.2
  awesome_dialog: ^3.2.0
  firebase_app_check: ^0.2.1+18
  go_router: ^13.2.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  equatable: ^2.0.5
  share: ^2.0.4
  drop_down_list: ^0.0.6
  url_launcher: ^6.0.6
  autocomplete_textfield: ^2.0.1
  carousel_slider: ^4.2.1 
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  mailer: ^5.0.0












dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterfire_cli: 

    


  
  flutter_lints: ^3.0.1


flutter:

  
  uses-material-design: true

  assets:
    
     
     - images/pass-login.png
     - images/background-login.jpeg
     - images/login-background-100.jpeg
     - images/email-login.png
     - images/spare-parts-logo.png
     - images/user-name-icon.jpeg
     - images/google-icon.png
     - images/eyadpic.jpg
     - images/apple-logo (1).png
     - images/LogoOfProjectBlack.png
     - images/LogoOfProject3.png
     - images/instagram.png
     - images/facebook.png
     - images/linkedin.png
     - images/phone_number.jpg
     - images/Advir.jpg
     - images/Advir3.jpg
     - images/Advir2.jpg
     - images/Advir.webp
     - images/Advir4.jpg
     - images/Advir5.jpg
     - images/forgot.png
     - images/engineRed.png
     - images/transmission.png
     - images/suspension.png
     - images/tranmioo.png
     - images/Bodycar.png
     - images/240_F_541751991_vbk7qqrqaHOzxHfliA9Giq8zc6qYUwdw.jpg
     - images/depositphotos_325830262-stock-photo-car-parts-black-background-copy.jpg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
