// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxpuBIcSqShC0q6cXgjh2bypCg6JOGz7c',
    appId: '1:872183292907:web:b833ee99f201767c81afae',
    messagingSenderId: '872183292907',
    projectId: 'spare-parts-cb983',
    authDomain: 'spare-parts-cb983.firebaseapp.com',
    storageBucket: 'spare-parts-cb983.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAu1oCr2IR2uVE60ENHlCgFdGp-QcLUt4',
    appId: '1:872183292907:android:a0fa04e66ef2bcdb81afae',
    messagingSenderId: '872183292907',
    projectId: 'spare-parts-cb983',
    storageBucket: 'spare-parts-cb983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmUmcKQxMQjUSx2ggs0mX6YBkXwaO4tms',
    appId: '1:872183292907:ios:c129d8e6fa25990381afae',
    messagingSenderId: '872183292907',
    projectId: 'spare-parts-cb983',
    storageBucket: 'spare-parts-cb983.appspot.com',
    iosBundleId: 'com.example.spareparts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmUmcKQxMQjUSx2ggs0mX6YBkXwaO4tms',
    appId: '1:872183292907:ios:2c481aafbb8d81fb81afae',
    messagingSenderId: '872183292907',
    projectId: 'spare-parts-cb983',
    storageBucket: 'spare-parts-cb983.appspot.com',
    iosBundleId: 'com.example.spareparts.RunnerTests',
  );
}
