// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWVJfAovk-8OviTF3Fybaff3fHLqoMeiQ',
    appId: '1:990017565076:web:604ab6942d2355c1171f81',
    messagingSenderId: '990017565076',
    projectId: 'spareparts-c3f23',
    authDomain: 'spareparts-c3f23.firebaseapp.com',
    storageBucket: 'spareparts-c3f23.appspot.com',
    measurementId: 'G-8GXSMC2GH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxm6LZLKXyiZ23kkR8fcN-iTVHMoed5l0',
    appId: '1:990017565076:android:4783429ad7fbfa06171f81',
    messagingSenderId: '990017565076',
    projectId: 'spareparts-c3f23',
    storageBucket: 'spareparts-c3f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHuYwBnbYDkC-etcVmrRhdI0Mby0WI5U',
    appId: '1:990017565076:ios:d150908f94651c8a171f81',
    messagingSenderId: '990017565076',
    projectId: 'spareparts-c3f23',
    storageBucket: 'spareparts-c3f23.appspot.com',
    iosBundleId: 'com.example.spareparts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnHuYwBnbYDkC-etcVmrRhdI0Mby0WI5U',
    appId: '1:990017565076:ios:fb58393ce18daf2a171f81',
    messagingSenderId: '990017565076',
    projectId: 'spareparts-c3f23',
    storageBucket: 'spareparts-c3f23.appspot.com',
    iosBundleId: 'com.example.spareparts.RunnerTests',
  );
}
